config/routes.rb
Rails.application.routes.draw do

  root 'users#login'

  get 'users/availability'
  post 'users/availability', to: 'users#availability_post'
  get 'users/profile'

  get 'users/subboard'
  get 'users/subboard_remove/:tour_id', to: 'users#subboard_remove'
  get 'users/subboard_claim/:tour_id', to: 'users#subboard_claim'
  get 'users/points'
  get 'users/check_in'
  get 'users/password'
  post 'users/check_in', to: 'users#check_in_post'
  get 'users/list', to: 'users#list'
  get 'users/reset_points', to: 'users#reset_points'
  get 'users/:id', to: 'users#delete'
  get 'users/make_admin/:id', to: 'users#make_admin'
  get 'users/revoke_admin/:id', to: 'users#revoke_admin'
  get 'users/manual_check_in/:user_id/:tour_id/:tour_given', to: 'users#manual_check_in'
  patch 'users/change_points/:id', to: 'users#change_points'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'users#login'
  post 'login', to: 'users#login_submit'
  get 'logout', to: 'users#logout'
  post 'password', to: 'users#update_password'

  get 'tours/new'
  post 'tours/create'
  get 'tours/manage'
  get 'tours/delete_all', to: 'tours#delete_all'
  get 'tours/scheduler', to: 'tours#scheduler'
  post 'tours/scheduler', to: 'tours#scheduler_post'
  get 'tours/:id', to: 'tours#delete'
  get 'tours/manage/:id', to: 'tours#manage_guides'
  get 'tours/remove_guide/:tour_id/:user_id', to: 'tours#remove_guide'
  get 'tours/add_guide/:tour_id/:user_id', to: 'tours#add_guide'
  get 'tours/view_guides/:id', to: 'tours#view_guides'
  patch 'tours/change_location/:id', to: 'tours#change_location'
  patch 'tours/change_notes/:id', to: 'tours#change_notes'
  patch 'tours/change_num_guides/:id', to: 'tours#change_num_guides'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@vanderbilt.edu\z/, message: 'Invalid email' }
    validates :first_name, presence: true
    validates :last_name, presence: true
    has_and_belongs_to_many :tours

    #Function to clear availability
    def clear_availability
        false_hash = {}
        ["mon", "tues", "wed", "thur", "fri", "sat", "sun"].each do |day|
            ["_9", "_9:30", "_10", "_10:30", "_11", 
              "_11:30", "_12", "_12:30", "_1", "_1:30",
              "_2", "_2:30", "_3", "_3:30", "_4", "_4:30",
              "_5", "_5:30"].each do |time|
              false_hash["#{day}#{time}".to_sym] = false
            end
          end
          update(false_hash)
    end

    #Function to determine if a user has any availability entered
    def has_availability
      ["mon", "tues", "wed", "thur", "fri", "sat", "sun"].each do |day|
        ["_9", "_9:30", "_10", "_10:30", "_11", 
          "_11:30", "_12", "_12:30", "_1", "_1:30",
          "_2", "_2:30", "_3", "_3:30", "_4", "_4:30",
          "_5", "_5:30"].each do |time|
          if send("#{day}#{time}")
            return true
          end
        end
      end
      false
    end

    #Function to properly display a user's name
    def name_display
      "#{first_name} #{last_name}"
    end

    #Function to determine if a user is available for a certain time
    def is_available(times)
      times.each do |time|
        if !send(time)
          return false
        end
      end
      true
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  #Function to store data with all users
  def points
    if !session[:user_id]
      redirect_to root_path
    end
    @data = User.all
  end

  #Function to direct to correct rootpath based upon whether availability has been entered
  def availability
    if !session[:user_id] || !User.find(session[:user_id])
      redirect_to root_path
    end
  end

  #Function to fill the availability part of database for a user
  def availability_post
    if !session[:user_id]
      redirect_to root_path
    end
    new_params = {}
    params.each do |k, v|
      if v == "on"
        new_params[k] = true
      end
    end
    @user = User.find(session[:user_id])
    @user.clear_availability
    @user.update(new_params)
    flash[:success] = "Availability Updated"
    redirect_to root_path
  end

  def check_in
    if !session[:user_id]
      redirect_to root_path
    end
  end

  #Function to check in and update user's points if in the correct time
  def check_in_post
    if !session[:user_id]
      redirect_to root_path
    end
    @user = User.find(session[:user_id])
    @tour = Tour.find(params[:tour_id])
    if @tour.time - 15*60 < current_time && @tour.time + 15*60 > current_time
      if(params[:tour_given])
        @user.points = @user.points + 1
        @user.save
      end
      @tour.checked_in_email << @user.email
      @tour.save
      flash[:success] = "Checked In"
    else
      flash[:danger] = "Not the right time"
    end
    redirect_back(fallback_location: root_path)
  end

  #Function to update user points if told to do so by an administrator
  def manual_check_in
    check_admin()
    @user = User.find(params[:user_id])
    @tour = Tour.find(params[:tour_id])
    if(params[:tour_given] == "true")
      @user.points = @user.points + 1
      @user.save
    end
    @tour.checked_in_email << @user.email
    @tour.save
    redirect_back(fallback_location: root_path)
  end

  def profile
    if !session[:user_id]
      redirect_to root_path
    end
  end

  def subboard
    if !session[:user_id]
      redirect_to root_path
    end
  end

  def change_points
    check_admin()
    @user = User.find(params[:id])
    @user.update_attribute(:points, params[:points])
    redirect_to root_path
end

  #Function to store user variable with a new user
  def new
    @user = User.new
  end

  def login
    if session[:user_id] && User.find(session[:user_id])
      redirect_to users_profile_path
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to login_path
  end

  #Funciton to list all guides
  def list
    check_admin()
    User.all.each do |user|
      absences = 0
      user.tours.all.select {|tour| tour.end_time < current_time}.each do |tour|
        logger.debug(tour.display)
        if (!tour.checked_in_email.include? user.email)
          absences = absences + 1
        end
      end
      user.absences = absences
      user.save
    end
  end

  #Function to reset all points
  def reset_points
    check_admin()
    User.all.each do |user|
      user.points = 0
      user.save
    end
    redirect_back(fallback_location: root_path)
  end

  #Function to login
  def login_submit
    @user = User.find_by_email(params[:email])
    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:danger] = "Error: Incorrect username or password"
      redirect_to login_path
    end
  end

  #Function to create a new user
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Success"
      redirect_to users_availability_path
    elsif @user.first_name == ""
      flash.now[:danger] = "Please enter a first name"
      render :new
    elsif @user.last_name == ""
      flash.now[:danger] = "Please enter a last name"
      render :new
    else
      flash.now[:danger] = "Please enter a valid email"
      render :new
    end
  end

  def update_password
    @user1 = User.find_by_email(params[:email])
    if @user1 && @user1.update_attribute(:password, params[:password])
      flash.now[:success] = "Password has been changed!"
      render :availability
    else
      flash.now[:danger] = "User not found. Please try again."
      render :availability
    end
  end

  #Function to remove a tour from the subboard
  def subboard_remove
    if !session[:user_id]
      redirect_to root_path
    end
    user = User.find(session[:user_id])
    @tour = Tour.find(params[:tour_id])
    user.tours.delete(@tour)
    redirect_to users_subboard_path
  end 

  #Function to claim a tour from the subboard
  def subboard_claim
    if !session[:user_id]
      redirect_to root_path
    end
    user = User.find(session[:user_id])
    @tour = Tour.find(params[:tour_id])
    user.tours.append @tour
    redirect_to users_subboard_path
  end

  #Function to delete a user
  def delete
    check_admin()
    @user = User.find(params[:id])
    if @user.id == session[:user_id]
      flash[:danger] = "You cannot delete yourself"
      redirect_back(fallback_location: root_path)
      return
    end
    @user.delete
    redirect_back(fallback_location: root_path)
  end

  #Function to make a user an admin
  def make_admin
    check_admin()
    @user = User.find(params[:id])
    @user.administrator = true
    @user.save
    redirect_back(fallback_location: root_path)
  end

  #Function to remove administrative priviledges from an admin
  def revoke_admin
    check_admin()
    @user = User.find(params[:id])
    if @user.id == session[:user_id]
      flash[:danger] = "You cannot revoke your own admin status"
      redirect_back(fallback_location: root_path)
      return
    end
    @user.administrator = false
    @user.save
    redirect_back(fallback_location: root_path)
  end

  private
  #Function to check if a user is an admin
  def check_admin
    if !session[:user_id] || !User.find(session[:user_id]).administrator
        redirect_to root_path
    end
  end

  #Function to fill a user with specified parameters
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  #Function to use the availability
  def availability_params
    params.permit(
      ["mon", "tues", "wed", "thur", "fri", "sat", "sun"].each do |day|
        ["_9", "_9:30", "_10", "_10:30", "_11", 
          "_11:30", "_12", "_12:30", "_1", "_1:30",
          "_2", "_2:30", "_3", "_3:30", "_4", "_4:30",
          "_5", "_5:30"].each do |time|
            "#{day}#{time}"
          end
        end
    )
    
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/availability.html.erb
<% @user = current_user %>

<div class="container-fluid">
    <h1 class="text-center my-4">User Availability</h1>
    <form id="availability" class="input-group justify-content-center" method="post">
        <div class="row justify-content-center white-background my-2" style="overflow-x:auto;">
            <table class="text-center col-md-8 my-2">
                <thead>
                    <td>Mon</td>
                    <td>Tue</td>
                    <td>Wed</td>
                    <td>Thu</td>
                    <td>Fri</td>
                    <td>Sat</td>
                    <td>Sun</td>
                </thead>
                <tbody>
                    <% days = ["mon", "tues", "wed", "thur", "fri", "sat", "sun"] %>
                    <% days.each { |day|%>
                        <td class="form-control-md  " id=<%= day%>>
                            <input type="checkbox" class="btn-check" id="<%= day%>_9" name="<%= day%>_9" <%= @user.send("#{day}_9") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_9"> 9:00 a.m. - 9:30 a.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_9:30" name="<%= day%>_9:30" <%= @user.send("#{day}_9:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_9:30">9:30 a.m. - 10:00 a.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_10" name="<%= day%>_10" <%= @user.send("#{day}_10") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_10">10:00 a.m. - 10:30 a.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_10:30" name="<%= day%>_10:30" <%= @user.send("#{day}_10:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_10:30">10:30 a.m. - 11:00 a.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_11" name="<%= day%>_11" <%= @user.send("#{day}_11") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_11">11:00 a.m. - 11:30 a.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_11:30" name="<%= day%>_11:30" <%= @user.send("#{day}_11:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_11:30">11:30 a.m. - 12:00 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_12" name="<%= day%>_12" <%= @user.send("#{day}_12") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_12">12:00 p.m. - 12:30 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_12:30" name="<%= day%>_12:30" <%= @user.send("#{day}_12:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_12:30">12:30 p.m. - 1:00 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_1" name="<%= day%>_1" <%= @user.send("#{day}_1") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_1">1:00 p.m. - 1:30 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_1:30" name="<%= day%>_1:30" <%= @user.send("#{day}_1:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_1:30">1:30 p.m. - 2:00 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_2" name="<%= day%>_2" <%= @user.send("#{day}_2") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_2">2:00 p.m. - 2:30 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_2:30" name="<%= day%>_2:30" <%= @user.send("#{day}_2:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_2:30">2:30 p.m. - 3:00 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_3" name="<%= day%>_3" <%= @user.send("#{day}_3") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_3">3:00 p.m. - 3:30 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_3:30" name="<%= day%>_3:30" <%= @user.send("#{day}_3:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_3:30">3:30 p.m. - 4:00 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_4" name="<%= day%>_4" <%= @user.send("#{day}_4") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_4">4:00 p.m. - 4:30 p.m.</label>
                            <br>
                            <input type="checkbox" class="btn-check" id="<%= day%>_4:30" name="<%= day%>_4:30" <%= @user.send("#{day}_4:30") ? "checked" : nil %>>
                            <label class="btn btn-outline-primary shadow-none" for="<%= day%>_4:30">4:30 p.m. - 5:00 p.m.</label>
                    </td>
                    <% } %>
                </tbody>
            </table>
            <div class="justify-content-center row">
                <input class="btn btn-primary col-md-2 my-2 shadow-none" type="submit" value="Submit"/>
            </div>
        </div>
    </form>
</div>

app/views/users/list.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Guide List</h1>

    <div class="row">
        <div class="col-md-10 offset-md-1 my-2 white-background" id="guideTables">
            <div class="d-flex justify-content-end my-3" style="width:100%;">
                <%=button_to "Reset All Guides' Points", users_reset_points_path, method: :get, class: "btn btn-danger btn rounded-2 shadow-none", onclick: "return confirm('Are you sure you want to reset all points to 0?')"%>
            </div>
            <button class="myBtn btn btn-primary shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#allGuides" aria-expanded="true" aria-controls="allGuides">
                All Users
            </button>
            <button class="myBtn btn btn-primary shadow-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#adminGuides" aria-expanded="false" aria-controls="adminGuides">
                Admin Users
            </button>
            <button class="myBtn btn btn-primary shadow-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#normalGuides" aria-expanded="false" aria-controls="normalGuides">
                Non-Admin Users
            </button>
            <div class="collapse show" id="allGuides" data-bs-parent="#guideTables" style="overflow-x:auto; max-height:42vh;">
                <table class="table table-bordered">
                    <thead style="position:sticky; top:-0.1%; box-shadow: inset 1px 1px #000, 0 1px #000;">
                        <tr>
                            <th>Guide Name</th>
                            <th>Guide Email</th>
                            <th class="text-center">Guide Points</th>
                            <th class="text-center">Absences</th>
                            <th class="text-center">Admin?</th>
                            <th class="text-center">Change Admin Status</th>
                            <th class="text-center">Delete Guide</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% User.order(:last_name).all.each do |user| %>
                            <tr>
                                <td>
                                    <%= user.name_display %>
                                </td>
                                <td>
                                    <%= user.email %>
                                </td>
                                <td class="text-center">
                                    <%= form_with url: "change_points/#{user.id}", method: :patch do |form| %>
                                        <%= form.number_field :points, value: user.points, class: 'points-field' %>
                                        <%= form.submit "Submit Edit", class: 'submit-edit' %>
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <%= user.absences %>
                                </td>
                                <td class="text-center">
                                    <% if user.administrator %>
                                        Yes
                                    <% else %>
                                        No
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <% if user.administrator %>
                                        <a href=<%= "revoke_admin/#{user.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to revoke admin status from this user?')">
                                        Revoke Admin
                                        </a>
                                    <% else %>
                                        <a href=<%= "make_admin/#{user.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to give this user admin status?')">
                                        Make Admin
                                        </a>
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "#{user.id}" %> class="btn btn-danger btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to delete this user?')">
                                    Delete
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <div class="collapse" id="adminGuides" data-bs-parent="#guideTables" style="overflow-x:auto; max-height:42vh;">
                <table class="table table-bordered">
                    <thead style="position:sticky; top:-0.1%; box-shadow: inset 1px 1px #000, 0 1px #000;">
                        <tr>
                            <th>Guide Name</th>
                            <th>Guide Email</th>
                            <th class="text-center">Guide Points</th>
                            <th class="text-center">Absences</th>
                            <th class="text-center">Admin?</th>
                            <th class="text-center">Change Admin Status</th>
                            <th class="text-center">Delete Guide</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% User.order(:last_name).all.select{|user| user.administrator}.each do |user| %>
                            <tr>
                                <td>
                                    <%= user.name_display %>
                                </td>
                                <td>
                                    <%= user.email %>
                                </td>
                                <td class="text-center">
                                    <%= user.points %>
                                </td>
                                <td class="text-center">
                                    <%= user.absences %>
                                </td>
                                <td class="text-center">
                                    <% if user.administrator %>
                                        Yes
                                    <% else %>
                                        No
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <% if user.administrator %>
                                        <a href=<%= "revoke_admin/#{user.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to revoke admin status from this user?')">
                                        Revoke Admin
                                        </a>
                                    <% else %>
                                        <a href=<%= "make_admin/#{user.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to give this user admin status?')">
                                        Make Admin
                                        </a>
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "#{user.id}" %> class="btn btn-danger btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to delete this user?')">
                                    Delete
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <div class="collapse" id="normalGuides" data-bs-parent="#guideTables" style="overflow-x:auto; max-height:42vh;">
                <table class="table table-bordered">
                    <thead style="position:sticky; top:-0.1%; box-shadow: inset 1px 1px #000, 0 1px #000;">
                        <tr>
                            <th>Guide Name</th>
                            <th>Guide Email</th>
                            <th class="text-center">Guide Points</th>
                            <th class="text-center">Absences</th>
                            <th class="text-center">Admin?</th>
                            <th class="text-center">Change Admin Status</th>
                            <th class="text-center">Delete Guide</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% User.order(:last_name).all.select{|user| !user.administrator}.each do |user| %>
                            <tr>
                                <td>
                                    <%= user.name_display %>
                                </td>
                                <td>
                                    <%= user.email %>
                                </td>
                                <td class="text-center">
                                    <%= user.points %>
                                </td>
                                <td class="text-center">
                                    <%= user.absences %>
                                </td>
                                <td class="text-center">
                                    <% if user.administrator %>
                                        Yes
                                    <% else %>
                                        No
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <% if user.administrator %>
                                        <a href=<%= "revoke_admin/#{user.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to revoke admin status from this user?')">
                                        Revoke Admin
                                        </a>
                                    <% else %>
                                        <a href=<%= "make_admin/#{user.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to give this user admin status?')">
                                        Make Admin
                                        </a>
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "#{user.id}" %> class="btn btn-danger btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to delete this user?')">
                                    Delete
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/users/login.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Login</h1>
    <div class="d-flex justify-content-center my-2 white-background">
        <div>
            <%= form_tag '/login' do %>
                Email 
                <br>
                <%= text_field_tag :email %>
                <br>
                Password 
                <br>
                <%= password_field_tag :password %>
                <br>
                <div class="text-center mt-2">
                    <%= submit_tag "Log In", class: "btn btn-primary my-1 shadow-none" %>
                </div>
            <% end %>
            <div class="text-center mt-4 mb-2">
                Don't have an account?
                <%= button_to "Create one!", signup_path, method: :get, class: "btn btn-primary my-1 shadow-none" %>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Sign Up</h1>
    <div class="row">
        <div class="d-flex justify-content-center my-2 white-background">
            <div>
                <%= form_with model: @user, url: signup_path do |f| %>
                    <%= f.label 'first_name' %><br>
                    <%= f.text_field :first_name, value: nil %><br>
                    <%= f.label 'last_name' %><br>
                    <%= f.text_field :last_name, value: nil %><br>
                    <%= f.label 'email' %><br>
                    <%= f.email_field :email %><br>
                    <%= f.label 'password' %><br>
                    <%= f.password_field :password %><br>
                    <%= f.label 'password_confirmation' %><br>
                    <%= f.password_field :password_confirmation %><br><br>
                    <div class="text-center">
                        <%= f.submit 'Sign Up', class: "btn btn-primary my-1 shadow-none" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/password.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Password Reset</h1>
    <div class="d-flex justify-content-center my-2 white-background">
        <div>
        <%= form_tag '/password' do %>
                Email 
                <br>
                <%= text_field_tag :email %>
                <br>
                Password 
                <br>
                <%= password_field_tag :password %>
                <br>
                <div class="text-center mt-2">
                    <%= submit_tag "Reset Password", class: "btn btn-primary my-1 shadow-none" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/points.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Points</h1>
    <div class="row">
        <div class="col-md-4 offset-md-4 white-background">
            <div style="overflow-x:auto; max-height:65vh;">
                <table class="table table-bordered my-2">
                    <thead style="position:sticky; top:0%; box-shadow: inset 1px 1px #000, 0 1px #000;">
                        <tr>
                            <th>Name</th>
                            <th>Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @data.order(:last_name).each do |data| %>
                        <tr>
                            <td><%= data.name_display %></td>
                            <td><%= data.points %></td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>