config/routes.rb
Rails.application.routes.draw do

  root 'users#login'

  get 'users/availability'
  post 'users/availability', to: 'users#availability_post'
  get 'users/profile'

  get 'users/subboard'
  get 'users/subboard_remove/:tour_id', to: 'users#subboard_remove'
  get 'users/subboard_claim/:tour_id', to: 'users#subboard_claim'
  get 'users/points'
  get 'users/check_in'
  get 'users/password'
  post 'users/check_in', to: 'users#check_in_post'
  get 'users/list', to: 'users#list'
  get 'users/reset_points', to: 'users#reset_points'
  get 'users/:id', to: 'users#delete'
  get 'users/make_admin/:id', to: 'users#make_admin'
  get 'users/revoke_admin/:id', to: 'users#revoke_admin'
  get 'users/manual_check_in/:user_id/:tour_id/:tour_given', to: 'users#manual_check_in'
  patch 'users/change_points/:id', to: 'users#change_points'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'users#login'
  post 'login', to: 'users#login_submit'
  get 'logout', to: 'users#logout'
  post 'password', to: 'users#update_password'

  get 'tours/new'
  post 'tours/create'
  get 'tours/manage'
  get 'tours/delete_all', to: 'tours#delete_all'
  get 'tours/scheduler', to: 'tours#scheduler'
  post 'tours/scheduler', to: 'tours#scheduler_post'
  get 'tours/:id', to: 'tours#delete'
  get 'tours/manage/:id', to: 'tours#manage_guides'
  get 'tours/remove_guide/:tour_id/:user_id', to: 'tours#remove_guide'
  get 'tours/add_guide/:tour_id/:user_id', to: 'tours#add_guide'
  get 'tours/view_guides/:id', to: 'tours#view_guides'
  patch 'tours/change_location/:id', to: 'tours#change_location'
  patch 'tours/change_notes/:id', to: 'tours#change_notes'
  patch 'tours/change_num_guides/:id', to: 'tours#change_num_guides'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_and_belongs_to_many :users

    #Function to display a date in the proper format
    def date_display
        "#{time.strftime('%A')} #{time.month}/#{time.day}"
    end

    #Function to display a day in the proper format
    def day_display
        "#{time.strftime('%A')}"
    end

    #Function to fully display a tour
    def display
        "#{time.strftime('%A')} #{time.month}/#{time.day} #{time.strftime('%-I:%M')} - #{end_time.strftime('%-I:%M %p')}"
    end

    #Function to display a time in the proper format
    def time_display
        "#{time.strftime('%-I:%M %p')} - #{end_time.strftime('%-I:%M %p')}"
    end

    #Function to display a tour details in the proper format
    def details_display
        s = "Location: #{location}"
        if !note.empty?
            s += "\nNotes: #{note}"
        end
        s
    end

    #Function to determine if a time is in the current day
    def today?
        time < current_time + 1.day
    end

    def start_time
        current_time
    end

    #Function to properly format availability
    def availability
        case time.strftime('%A')
        when "Monday"
            base = "mon_"
        when "Tuesday"
            base = "tues_"
        when "Wednesday"
            base = "wed_"
        when "Thursday"
            base = "thur_"
        when "Friday"
            base = "fri_"
        when "Saturday"
            base = "sat_"
        when "Sunday"
            base = "sun_"
        end

        array = []

        start_num = time.strftime('%H').to_i
        start_thirty = time.strftime('%M').to_i >= 30

        end_num = end_time.strftime('%H').to_i
        add_thirty = end_time.strftime('%M').to_i > 30
        # if end_num < 9
        #     end_num += 12
        # end
        # if start_num < 9
        #     end_num += 12
        # end

        if start_thirty
            hour_num = start_num
            if start_num > 12
                hour_num -= 12
            end
            array << base + hour_num.to_s + ":30"
            start_num += 1
        end
        
        for hour in start_num..end_num do
            if hour > 12
                adj_hour = hour - 12
            else
                adj_hour = hour
            end
            array << base + adj_hour.to_s
            if hour != end_num || add_thirty
                array << base + adj_hour.to_s + ":30"
            end
        end

        array
    end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
    skip_before_action :verify_authenticity_token

    #Function to store tour variable with an empty tour
    def new
        check_admin()
        @tour = Tour.new
    end

    #Function for creating new tours given the set tour parameters
    def create
        check_admin()
        @tour = Tour.new(tour_params)
        @tour.end_time = @tour.time + params[:tour][:hours].to_i.hours
        @tour.save
        flash[:success] = "Tour Created"
        redirect_to tours_new_path
    end

    def manage
        check_admin()
    end

    #Function for deleting a tour by tour id
    def delete
        check_admin()
        Tour.find(params[:id]).delete
        redirect_back(fallback_location: root_path)
    end

    #Function for deleting all tours
    def delete_all
        check_admin()
        Tour.all.each do |tour|
            tour.delete
        end
        redirect_back(fallback_location: root_path)
    end

    #Function to store tour variable with tour found by an id
    def manage_guides
        check_admin()
        @tour = Tour.find(params[:id])
    end

    #Function to store tour variable with tour found by an id
    def view_guides
        check_admin()
        @tour = Tour.find(params[:id])
    end

    #Function for removing all guides on a tour
    def remove_guide
        check_admin()
        @tour = Tour.find(params[:tour_id])
        @user = User.find(params[:user_id])
        @tour.users.delete(@user)
        redirect_back(fallback_location: root_path)
    end

    #Function for adding a guide to a tour
    def add_guide
        check_admin()
        @tour = Tour.find(params[:tour_id])
        @user = User.find(params[:user_id])
        @tour.users.append @user
        redirect_back(fallback_location: root_path)
    end

    def change_location
        check_admin()
        @tour = Tour.find(params[:id])
        @tour.update_attribute(:location, (params[:location]))
        redirect_back(fallback_location: root_path)
    end

    def change_notes
        check_admin()
        @tour = Tour.find(params[:id])
        @tour.update_attribute(:note, params[:note])
        redirect_back(fallback_location: root_path)
    end

    def change_num_guides
        check_admin()
        @tour = Tour.find(params[:id])
        @tour.update_attribute(:min_guides, params[:num_guides])
        redirect_back(fallback_location: root_path)
    end

    def scheduler
    end

    #Function to perform the scheduling algorithm
    def scheduler_post
        #logger.debug("ENTERING SCHEDULING ALGO")
        #logger.debug()

        tours = Tour.select{|tour| tour.weekly} #creating an array of all tours with weekly tag
        scheduler = Hash.new

        #building a hash where each key is a tour and each value is an empty array
        tours.each do |tour|
            scheduler[tour] = Array.new
        end

        users = Array.new

        params[:guides].each do |email|
            @user = User.find_by_email(email)
            users.push(@user)
        end

        if(users[0] == nil)
            users.shift()
        end

        #creating arrays for the admins and non-admins
        admins = Array.new
        guides = Array.new

        users.each do |user|
            if(user.administrator && user.has_availability)
                admins.push(user)
            elsif(!user.administrator && user.has_availability)
                guides.push(user)
            end
        end

        #logger.debug("ADMINS = ")
        #admins.each do |admin|
            #logger.debug(admin.email)
        #end

        #logger.debug("GUIDES = ")
        #guides.each do |guide|
            #logger.debug(guide.email)
        #end
        #logger.debug()

        #creating a hash where the key is an admin user and the value is the number of tours they're available for
        adminAvailability = Hash.new
        admins.each do |admin|
            available = 0
            tours.each do |tour|
                if(admin.is_available(tour.availability))
                    available += 1
                end
            end
            adminAvailability[admin] = available
        end

        #adding the least available admins to a tour first until all tours have 1 admin or we've gone through all the admins
        adminAvailability.sort_by{|k, v| v}.each do |admin, _|
            tours.each do |tour|
                if(admin.is_available(tour.availability) && scheduler[tour].length == 0)
                    #logger.debug("admin added is: ")
                    #logger.debug(admin.email)

                    #logger.debug("tour added to is: ")
                    #logger.debug(tour.display)

                    scheduler[tour].push(admin)
                    admins.delete(admin)
                    break
                end
            end
        end

        #logger.debug("ADMINS ARE (should be none): ")
        #admins.each do |admin|
            #logger.debug(admin.email)
        #end

        #adding extra admins into normal guide pool
        guides = guides.concat(admins)

        #logger.debug("GUIDES ARE: ")
        #guides.each do |guide|
            #logger.debug(guide.email)
        #end
        #logger.debug()

        #creating a hash where the key is a tour and the value is the number of guides available for that tour
        tourAvailability = Hash.new
        tours.each do |tour|
            available = 0
            guides.each do |guide|
                if(guide.is_available(tour.availability))
                    available += 1
                end
            end
            tourAvailability[tour] = available
        end

        #creating a hash where the key is a guide and the value is the number of tours that guide is available for
        guideAvailability = Hash.new
        guides.each do |guide|
            available = 0
            tours.each do |tour|
                if(guide.is_available(tour.availability))
                    available += 1
                end
            end
            guideAvailability[guide] = available
        end

        #creating a hash where the key is a tour and the values is false (representing if the tour has been filled)
        filled = Hash.new
        tours.each do |tour|
            filled[tour] = false
        end

        #while there's still a tour that has guides available for it
        while(any_false(filled))
            #looking at the least available tour and attempting to fill it with the least available guide, adding 1 guide to a tour at a time
            tourAvailability.sort_by{|k, v| v}.each do |tour, _|
                if(filled[tour])
                    next
                end
                found = false
                guideAvailability.sort_by{|k, v| v}.each do |guide, _|
                    if(guide.is_available(tour.availability))
                        scheduler[tour].push(guide)

                        #logger.debug("guide added is: ")
                        #logger.debug(guide.email)

                        #logger.debug("tour added to is: ")
                        #logger.debug(tour.display)

                        guides.delete(guide)
                        guideAvailability.delete(guide)
                        found = true
                        break
                    end
                end
                if(!found)
                    filled[tour] = true
                end
            end
        end

        #logger.debug()
        #logger.debug("ENTERING TOUR CREATION")
        #logger.debug()

        #creating all of the tours in the system
        tours.each do |tour|
            for week in 0..(tour.weeks - 1)
                tempTour = tour.dup()
                tempTour.weekly = false
                tempTour.weeks = 1
                tempTour.time += week.weeks
                tempTour.end_time += week.weeks
                tempTour.min_guides = scheduler[tour].length
                tempTour.save
                #logger.debug("TEMP TOUR INFO: ")
                #logger.debug(tempTour.display)
                #logger.debug("guide: ")
                if(tempTour.users[0]) 
                    #logger.debug(tempTour.users[0].email)
                    tempTour.users = []
                end
                #logger.debug()
                scheduler[tour].each do |guide|
                    tempTour.users.append(guide)
                    #logger.debug("Adding guide: ")
                    #logger.debug(guide.email)

                    #logger.debug("Adding to tour: ")
                    #logger.debug(tour.display)
                end
            end
            tour.delete
        end

        #displaying guides that were unable to be scheduled
        temp = "The following guides were not scheduled:"
        guides.each do |guide|
            temp +=  " " + guide.name_display + ","
        end
        flash[:danger] = temp
        redirect_to tours_scheduler_path

    end

    private

    #Function that is determining if there are any false values in a hash
    def any_false(hash)
        hash.each do |_, v|
            if v == false
                return true
            end
        end
        false
    end

    #Function to determine if a User is an admin
    def check_admin
        if !session[:user_id] || !User.find(session[:user_id]).administrator
            redirect_to root_path
        end
    end

    #Function to get the parameters of a tour
    def tour_params
        params.require(:tour).except(:hours).permit(:time, :min_guides, :location, :note, :weekly, :weeks)
    end

end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/manage.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Manage Tours</h1>

    <div class="row">
        <div class="col-md-8 offset-md-2 my-2 white-background" id="tourTables">
            <div class="d-flex justify-content-end my-3" style="width:100%;">
                <%=button_to "Delete All Tours", tours_delete_all_path, method: :get, class: "btn btn-danger btn rounded-2 shadow-none", onclick: "return confirm('Are you sure you want to delete all tours?')"%>
            </div>
            <button class="myBtn btn btn-primary shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#upcomingTours" aria-expanded="true" aria-controls="upcomingTours">
                Upcoming Tours
            </button>
            <button class="myBtn btn btn-primary shadow-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#pastTours" aria-expanded="false" aria-controls="pastTours">
                Past Tours
            </button>
            <button class="myBtn btn btn-primary shadow-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#weeklyTours" aria-expanded="false" aria-controls="weeklyTours">
                Weekly Tours
            </button>
            <div class="collapse show" id="upcomingTours" data-bs-parent="#tourTables" style="overflow-x:auto; max-height:42vh;">
                <table class="table table-bordered">
                    <thead style="position:sticky; top:-0.1%; box-shadow: inset 1px 1px #000, 0 1px #000;">
                        <tr>
                            <th class="text-center">Tour Date</th>
                            <th class="text-center">Tour Time</th>
                            <th class="text-center">Location</th>
                            <th class="text-center">Notes</th>
                            <th class="text-center">Num. of Guides</th>
                            <th class="text-center">Manage Guides</th>
                            <th class="text-center">Delete Tour</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% Tour.order(:time).all.select{|tour| !tour.weekly && tour.end_time > current_time}.each do |tour| %>
                            <tr>
                                <td class="text-center">
                                    <%= tour.date_display %>
                                </td>
                                <td class="text-center">
                                    <%= tour.time_display %>
                                </td>
                                <td>
                                    <%= form_with url: "change_location/#{tour.id}", method: :patch do |form| %>
                                        <%= form.text_field :location, :size=>"6%", value: tour.location %>
                                        <%= form.submit "Submit Edit", class: 'submit-edit' %>
                                    <% end %>
                                </td>
                                <td>
                                    <%= form_with url: "change_notes/#{tour.id}", method: :patch do |form| %>
                                        <%= form.text_field :note, :size=>"20%", value: tour.note %>
                                        <%= form.submit "Submit Edit", class: 'submit-edit' %>
                                    <% end %>
                                </td>
                                <td>
                                    <%= form_with url: "change_num_guides/#{tour.id}", method: :patch do |form| %>
                                        <%= form.number_field :num_guides, value: tour.min_guides, class: 'num-guides-field' %>
                                        <%= form.submit "Submit Edit", class: 'submit-edit' %>
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "/tours/manage/#{tour.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none">
                                    Click to Manage Guides
                                    </a>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "#{tour.id}" %> class="btn btn-danger btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to delete this tour?')">
                                    Delete
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <div class="collapse" id="pastTours" data-bs-parent="#tourTables" style="overflow-x:auto; max-height:42vh;">
                <table class="table table-bordered">
                    <thead style="position:sticky; top:-0.1%; box-shadow: inset 1px 1px #000, 0 1px #000;">
                        <tr>
                            <th>Tour Date</th>
                            <th>Tour Time</th>
                            <th>Location</th>
                            <th>Notes</th>
                            <th class="text-center">View Guides</th>
                            <th class="text-center">Delete Tour</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% Tour.order('time DESC').all.select{|tour| !tour.weekly && tour.end_time < current_time}.each do |tour| %>
                            <tr>
                                <td>
                                    <%= tour.date_display %>
                                </td>
                                <td>
                                    <%= tour.time_display %>
                                </td>
                                <td>
                                    <%= form_with url: "change_location/#{tour.id}", method: :patch do |form| %>
                                        <%= form.text_field :location, :size=>"6%", value: tour.location %>
                                        <%= form.submit "Change Location" %>
                                    <% end %>
                                </td>
                                <td>
                                    <%= form_with url: "change_notes/#{tour.id}", method: :patch do |form| %>
                                        <%= form.text_field :note, :size=>"20%", value: tour.note %>
                                        <%= form.submit "Submit Edit", class: 'submit-edit' %>
                                    <% end %>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "/tours/view_guides/#{tour.id}" %> class="btn btn-primary btn-sm rounded-2 shadow-none">
                                    Click to View Guides
                                    </a>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "#{tour.id}" %> class="btn btn-danger btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to delete this tour?')">
                                    Delete
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <div class="collapse" id="weeklyTours" data-bs-parent="#tourTables" style="overflow-x:auto; max-height:42vh;">
                <table class="table table-bordered">
                    <thead style="position:sticky; top:-0.1%; box-shadow: inset 1px 1px #000, 0 1px #000;">
                        <tr>
                            <th>Tour Day</th>
                            <th>Tour Time</th>
                            <th>Location</th>
                            <th>Notes</th>
                            <th class="text-center">Number of Weeks</th>
                            <th class="text-center">Delete Tour</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% Tour.order(:time).all.select{|tour| tour.weekly}.each do |tour| %>
                            <tr>
                                <td>
                                    <%= tour.day_display %>
                                </td>
                                <td>
                                    <%= tour.time_display %>
                                </td>
                                <td>
                                    <%= tour.location %>
                                </td>
                                <td>
                                    <%= tour.note %>
                                </td>
                                <td class="text-center">
                                    <%= tour.weeks %>
                                </td>
                                <td class="text-center">
                                    <a href=<%= "#{tour.id}" %> class="btn btn-danger btn-sm rounded-2 shadow-none" onclick="return confirm('Are you sure you want to delete this tour?')">
                                    Delete
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/tours/manage_guides.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Manage Guides</h1>
    <h4 class="text-center my-4"><%= @tour.display %></h4>
    <h4 class="text-center my-4">Location: <%= @tour.location %></h4>
    <% if @tour.note != "" %>
        <h4 class="text-center my-4">Notes: <%= @tour.note %></h4>
    <% end %>
    <div class="row">
        <div class="col-md-4 offset-md-1 mb-5 mb-lg-0 col-white-background" style="max-height: 55vh;">
            <h3 class="text-center my-2">On Tour</h3>
            <div class="overflow-auto" style="max-height:90%;">
                <table class="table table-bordered text-center">
                    <tbody>
                        <% @tour.users.order(:last_name).all.each do |user| %>
                            <tr>
                                <td>
                                    <%= user.name_display %>
                                </td>
                                <td>
                                    <a href=<%= "/tours/remove_guide/#{@tour.id}/#{user.id}" %> class="btn btn-primary my-1 shadow-none">
                                        Remove
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <% if @tour.users.size == 0 %>
                <h5 class="text-center">
                    There are no guides on this tour
                </h5>
            <% end %>
        </div>
        <div class="col-md-4 offset-md-2 mb-3 mb-lg-0 col-white-background" style="max-height: 55vh;">
            <h3 class="text-center my-2">Not on Tour</h3>
            <div class="overflow-auto" style="max-height: 90%;">
                <table class="table table-bordered text-center">
                    <tbody>
                        <% User.order(:last_name).all.select{|user| !@tour.users.member?(user)}.each do |user| %>
                            <tr>
                                <td>
                                <%= user.name_display %>
                                </td>
                                <td>
                                    <a href=<%= "/tours/add_guide/#{@tour.id}/#{user.id}" %> class="btn btn-primary my-1 shadow-none">
                                        Add
                                    </a>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <% if User.all.select{|user| !@tour.users.member?(user)}.size == 0 %>
                <h5 class="text-center">
                    All guides are assigned to this tour
                </h5>
            <% end %>
        </div>
    </div>
</div>

app/views/tours/new.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">New Tour</h1>
    <div class="row">
        <div class="d-flex justify-content-center input-group my-2 white-background">
            <div>
                <%= form_with model: @tour, url: tours_create_path do |f| %>
                    <%= f.label 'time' %><br>
                    <%= f.datetime_field :time %><br>
                    <%= f.label 'hours' %><br>
                    <%= f.number_field :hours %><br>
                    <%= f.label 'guides' %><br>
                    <%= f.number_field :min_guides %><br>
                    <%= f.label 'location' %><br>
                    <%= f.select :location, ['SLC', 'HOG', 'Sarratt', 'Other'] %><br>
                    <%= f.label 'note' %><br>
                    <%= f.text_field :note, :size => 30 %><br>
                    <%= f.label 'weekly?' %>
                    <%= f.check_box :weekly %><br>
                    <%= f.label 'weeks' %><br>
                    <%= f.number_field :weeks %><br><br>
                    <%= f.submit "Create Tour", class: "btn btn-primary my-1 shadow-none" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/tours/scheduler.html.erb
<div class="container-fluid">
    <h1 class="text-center my-4">Tour Scheduler</h1>

    <div class="row">
        <div class="col-md-4 offset-md-4 white-background">
            <h3 class="text-center">
                Weekly Tours
            </h3>
            <div style="max-height:50vh; overflow-x:auto; border-style:solid;">
                <table class="table table-bordered text-center">
                    <tbody>       
                        <% Tour.order(:time).all.select{|tour| tour.weekly && tour.time > current_time}.each do |tour| %>
                            <tr>
                                <td>
                                    <%= tour.display %> (<%= tour.weeks %> weeks)
                                </td>
                            </tr> 
                        <% end %>
                    </tbody>
                </table>
            </div>
            <h3 class="text-center">
                Select Guides
            </h3>
            <div style="max-height:50vh; overflow-x:auto; border-style:solid;">
                <div style="margin-left:5px">
                    <%= form_with url: "scheduler/", method: :post do |form| %>
                        <%= form.collection_check_boxes(:guides, User.order(:last_name).all, :email, :name_display) do |b| %>
                            <br>
                            <%= b.label class:"label-checkbox" do%>
                            <%=b.check_box + b.text%>
                            <% end %>
                        <% end %>
                        <br>
                        <div style="text-align:center;">
                        <%= form.submit "Schedule", {class: "btn btn-primary btn-sm rounded-2 shadow-none my-2"} %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>