config/routes.rb
Rails.application.routes.draw do

  root 'users#login'

  get 'users/availability'
  post 'users/availability', to: 'users#availability_post'
  get 'users/profile'

  get 'users/subboard'
  get 'users/subboard_remove/:tour_id', to: 'users#subboard_remove'
  get 'users/subboard_claim/:tour_id', to: 'users#subboard_claim'
  get 'users/points'
  get 'users/check_in'
  get 'users/password'
  post 'users/check_in', to: 'users#check_in_post'
  get 'users/list', to: 'users#list'
  get 'users/reset_points', to: 'users#reset_points'
  get 'users/:id', to: 'users#delete'
  get 'users/make_admin/:id', to: 'users#make_admin'
  get 'users/revoke_admin/:id', to: 'users#revoke_admin'
  get 'users/manual_check_in/:user_id/:tour_id/:tour_given', to: 'users#manual_check_in'
  patch 'users/change_points/:id', to: 'users#change_points'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'users#login'
  post 'login', to: 'users#login_submit'
  get 'logout', to: 'users#logout'
  post 'password', to: 'users#update_password'

  get 'tours/new'
  post 'tours/create'
  get 'tours/manage'
  get 'tours/delete_all', to: 'tours#delete_all'
  get 'tours/scheduler', to: 'tours#scheduler'
  post 'tours/scheduler', to: 'tours#scheduler_post'
  get 'tours/:id', to: 'tours#delete'
  get 'tours/manage/:id', to: 'tours#manage_guides'
  get 'tours/remove_guide/:tour_id/:user_id', to: 'tours#remove_guide'
  get 'tours/add_guide/:tour_id/:user_id', to: 'tours#add_guide'
  get 'tours/view_guides/:id', to: 'tours#view_guides'
  patch 'tours/change_location/:id', to: 'tours#change_location'
  patch 'tours/change_notes/:id', to: 'tours#change_notes'
  patch 'tours/change_num_guides/:id', to: 'tours#change_num_guides'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<div class="row">  
  <nav class="navbar navbar-expand-lg navbar-light dropdown">
      <div class="navbar-brand">
          <%= image_tag "VUTG_Logo.png", :class => "navbar-brand" %>
      </div>

      <button class="navbar-toggler" type="button" id="navbarCollapse" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="nav navbar-nav">
          <% if logged_in? %>
            <% if administrator? %>
              <li class="nav-item dropdown show">
                <a class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Admin
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/tours/new">Tour Creator</a>
                  <a class="dropdown-item" href="/tours/manage">Tour Manager</a>
                  <a class="dropdown-item" href="/users/list">Guide List</a>
                  <a class="dropdown-item" href="/users/password">Password Reset</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/tours/scheduler">Scheduler</a>
                </div>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to "Availability", users_availability_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Schedule", users_profile_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Points", users_points_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sub Board", users_subboard_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "Check In", users_check_in_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav ms-auto">
          <% if logged_in? %>
            <li class="nav-item dropdown show">
              <a class="nav-link dropdown-toggle" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                </svg>
                <%= "#{current_user.first_name} #{current_user.last_name}" %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href=/logout>Log Out</a>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", signup_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log In", login_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vandy Tour Guides</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body class="container-fluid">
    <%= render "layouts/navbar" %>
    <div>
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>">
          <%= msg %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>